// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	NodeDetailsVerbose
	NodeDetails
	NodeNetworkDetails
	ExecutionResponse
	ExecutionRequest
	Empty
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeDetailsVerbose struct {
	Summary *NodeDetails `protobuf:"bytes,1,opt,name=summary" json:"summary,omitempty"`
}

func (m *NodeDetailsVerbose) Reset()                    { *m = NodeDetailsVerbose{} }
func (m *NodeDetailsVerbose) String() string            { return proto.CompactTextString(m) }
func (*NodeDetailsVerbose) ProtoMessage()               {}
func (*NodeDetailsVerbose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeDetailsVerbose) GetSummary() *NodeDetails {
	if m != nil {
		return m.Summary
	}
	return nil
}

type NodeDetails struct {
	Version     string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Hostname    string                `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	ServicePort int32                 `protobuf:"varint,3,opt,name=service_port,json=servicePort" json:"service_port,omitempty"`
	Networks    []*NodeNetworkDetails `protobuf:"bytes,4,rep,name=networks" json:"networks,omitempty"`
}

func (m *NodeDetails) Reset()                    { *m = NodeDetails{} }
func (m *NodeDetails) String() string            { return proto.CompactTextString(m) }
func (*NodeDetails) ProtoMessage()               {}
func (*NodeDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeDetails) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeDetails) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeDetails) GetServicePort() int32 {
	if m != nil {
		return m.ServicePort
	}
	return 0
}

func (m *NodeDetails) GetNetworks() []*NodeNetworkDetails {
	if m != nil {
		return m.Networks
	}
	return nil
}

type NodeNetworkDetails struct {
	Interface  string `protobuf:"bytes,1,opt,name=interface" json:"interface,omitempty"`
	IpAddress  string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	MacAddress string `protobuf:"bytes,3,opt,name=mac_address,json=macAddress" json:"mac_address,omitempty"`
}

func (m *NodeNetworkDetails) Reset()                    { *m = NodeNetworkDetails{} }
func (m *NodeNetworkDetails) String() string            { return proto.CompactTextString(m) }
func (*NodeNetworkDetails) ProtoMessage()               {}
func (*NodeNetworkDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeNetworkDetails) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *NodeNetworkDetails) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *NodeNetworkDetails) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type ExecutionResponse struct {
	Command    string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	StdOut     string `protobuf:"bytes,2,opt,name=std_out,json=stdOut" json:"std_out,omitempty"`
	StdErr     string `protobuf:"bytes,3,opt,name=std_err,json=stdErr" json:"std_err,omitempty"`
	Background bool   `protobuf:"varint,4,opt,name=background" json:"background,omitempty"`
}

func (m *ExecutionResponse) Reset()                    { *m = ExecutionResponse{} }
func (m *ExecutionResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecutionResponse) ProtoMessage()               {}
func (*ExecutionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ExecutionResponse) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecutionResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *ExecutionResponse) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func (m *ExecutionResponse) GetBackground() bool {
	if m != nil {
		return m.Background
	}
	return false
}

type ExecutionRequest struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Context string `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
}

func (m *ExecutionRequest) Reset()                    { *m = ExecutionRequest{} }
func (m *ExecutionRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecutionRequest) ProtoMessage()               {}
func (*ExecutionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecutionRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecutionRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*NodeDetailsVerbose)(nil), "service.NodeDetailsVerbose")
	proto.RegisterType((*NodeDetails)(nil), "service.NodeDetails")
	proto.RegisterType((*NodeNetworkDetails)(nil), "service.NodeNetworkDetails")
	proto.RegisterType((*ExecutionResponse)(nil), "service.ExecutionResponse")
	proto.RegisterType((*ExecutionRequest)(nil), "service.ExecutionRequest")
	proto.RegisterType((*Empty)(nil), "service.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Checkin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeDetails, error)
	Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	Details(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeDetailsVerbose, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Checkin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeDetails, error) {
	out := new(NodeDetails)
	err := grpc.Invoke(ctx, "/service.Node/Checkin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	out := new(ExecutionResponse)
	err := grpc.Invoke(ctx, "/service.Node/Execute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Details(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeDetailsVerbose, error) {
	out := new(NodeDetailsVerbose)
	err := grpc.Invoke(ctx, "/service.Node/Details", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Checkin(context.Context, *Empty) (*NodeDetails, error)
	Execute(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	Details(context.Context, *Empty) (*NodeDetailsVerbose, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Checkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Checkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Node/Checkin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Checkin(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Node/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Execute(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Node/Details",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Details(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkin",
			Handler:    _Node_Checkin_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Node_Execute_Handler,
		},
		{
			MethodName: "Details",
			Handler:    _Node_Details_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0x92, 0xd6, 0xc9, 0x18, 0x10, 0x8c, 0x90, 0x30, 0x29, 0x7f, 0xc2, 0x9e, 0x72,
	0x8a, 0x44, 0x38, 0xc0, 0x15, 0x68, 0x38, 0x16, 0xe4, 0x03, 0xd7, 0x68, 0x63, 0x0f, 0x74, 0x15,
	0x76, 0xd7, 0xcc, 0xae, 0x4b, 0x7b, 0xe2, 0x51, 0x78, 0x0c, 0x5e, 0x0f, 0xc5, 0xde, 0x4d, 0xdd,
	0x2a, 0xea, 0x71, 0xe6, 0xf7, 0x8d, 0xbe, 0x6f, 0x67, 0x07, 0x1e, 0x38, 0xe2, 0x0b, 0x55, 0xd2,
	0xa2, 0x66, 0xeb, 0x2d, 0xa6, 0xa1, 0x14, 0xa7, 0x80, 0x67, 0xb6, 0xa2, 0x53, 0xf2, 0x52, 0xfd,
	0x74, 0xdf, 0x88, 0x37, 0xd6, 0x11, 0x2e, 0x20, 0x75, 0x8d, 0xd6, 0x92, 0xaf, 0xf2, 0x64, 0x96,
	0xcc, 0xb3, 0xe5, 0x93, 0x45, 0x9c, 0xef, 0xa9, 0x8b, 0x28, 0x12, 0x7f, 0x13, 0xc8, 0x7a, 0x00,
	0x73, 0x48, 0x2f, 0x88, 0x9d, 0xb2, 0xa6, 0x9d, 0x9f, 0x14, 0xb1, 0xc4, 0x29, 0x8c, 0xcf, 0xad,
	0xf3, 0x46, 0x6a, 0xca, 0xef, 0xb5, 0x68, 0x5f, 0xe3, 0x6b, 0xb8, 0x1f, 0x5c, 0xd6, 0xb5, 0x65,
	0x9f, 0x0f, 0x67, 0xc9, 0xfc, 0xa8, 0xc8, 0x42, 0xef, 0xab, 0x65, 0x8f, 0xef, 0x60, 0x6c, 0xc8,
	0xff, 0xb6, 0xbc, 0x75, 0xf9, 0x68, 0x36, 0x9c, 0x67, 0xcb, 0x93, 0x1b, 0xc9, 0xce, 0x3a, 0x18,
	0x03, 0xee, 0xc5, 0x82, 0xbb, 0x77, 0xde, 0xe4, 0xf8, 0x1c, 0x26, 0xca, 0x78, 0xe2, 0xef, 0xb2,
	0xa4, 0x90, 0xf4, 0xba, 0x81, 0x2f, 0x00, 0x54, 0xbd, 0x96, 0x55, 0xc5, 0xe4, 0x5c, 0x48, 0x3b,
	0x51, 0xf5, 0x87, 0xae, 0x81, 0xaf, 0x20, 0xd3, 0xb2, 0xdc, 0xf3, 0x61, 0xcb, 0x41, 0xcb, 0x32,
	0x08, 0xc4, 0x1f, 0x78, 0xbc, 0xba, 0xa4, 0xb2, 0xf1, 0xca, 0x9a, 0x82, 0x5c, 0x6d, 0x8d, 0xa3,
	0xdd, 0x6a, 0x4a, 0xab, 0xb5, 0x34, 0x55, 0x5c, 0x4d, 0x28, 0xf1, 0x29, 0xa4, 0xce, 0x57, 0x6b,
	0xdb, 0xf8, 0xe0, 0x75, 0xec, 0x7c, 0xf5, 0xa5, 0xf1, 0x11, 0x10, 0x73, 0x30, 0xd9, 0x81, 0x15,
	0x33, 0xbe, 0x04, 0xd8, 0xc8, 0x72, 0xfb, 0x83, 0x6d, 0x63, 0xaa, 0x7c, 0x34, 0x4b, 0xe6, 0xe3,
	0xa2, 0xd7, 0x11, 0x9f, 0xe1, 0x51, 0x2f, 0xc0, 0xaf, 0x86, 0x9c, 0xbf, 0xc3, 0xbf, 0x25, 0xc6,
	0xd3, 0x65, 0xf4, 0x8f, 0xa5, 0x48, 0xe1, 0x68, 0xa5, 0x6b, 0x7f, 0xb5, 0xfc, 0x97, 0xc0, 0x68,
	0xb7, 0x46, 0x7c, 0x03, 0xe9, 0xa7, 0x73, 0x2a, 0xb7, 0xca, 0xe0, 0xc3, 0xfd, 0x07, 0xb4, 0x9a,
	0xe9, 0xc1, 0x53, 0x11, 0x03, 0xfc, 0x08, 0x69, 0x17, 0x86, 0xf0, 0xd9, 0xf5, 0xc8, 0xad, 0x78,
	0xd3, 0xe9, 0x21, 0xd4, 0xad, 0x4e, 0x0c, 0xf0, 0x3d, 0xa4, 0xf1, 0xeb, 0x6e, 0xdb, 0x9e, 0x1c,
	0xb2, 0x0d, 0xf7, 0x2c, 0x06, 0x9b, 0xe3, 0xf6, 0xee, 0xdf, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x6a, 0xb2, 0xd9, 0x08, 0x03, 0x00, 0x00,
}
